cmd:         "/home/yeahyay/Programming/lua/love2d/love"
name:        "Love 2d"
args:
  - "./"
sh:          true
keymap:      ctrl-b
targets:
  "Kaitai Struct":
    cmd:     "ksc"
    name:    "Kaitai Struct"
    cwd:     "{FILE_ACTIVE_PATH}"
    args:
      - "-no-version-check"
      - "-v"
      - "-t lua"
      - "--outdir \"{FILE_ACTIVE_PATH}\""
      - "'{FILE_ACTIVE_NAME}'"
      # - "'{PROJECT_PATH}/src/Parsing/Kaitai_Struct/{FILE_ACTIVE_NAME}'"
    sh:      true
  "Windows":
    cmd:     "F:\\Programming\\Lua\\Love2D\\love-11.3-win64\\love"
    name:    "Love 2d"
    args:
      - "./"
    sh:      true
    keymap:  ctrl-b
  "Lizard":
    cmd:     "lizard"
    name:    "Lizard"
    args:
      - "./src"
      - "-t 4"
    sh:      true
    keymap:  ctrl-alt-shift-a
  "Lizard Duplicate":
    cmd:     "lizard"
    name:    "Lizard duplicate"
    args:
      - "-Eduplicate ./src"
    sh:      true
    keymap:  ctrl-alt-shift-d
